spring:
  application:
    name: sales-java

  data:
    mongodb:
      uri: mongodb://salesuser:salespass@192.168.1.122:27017/sales?authSource=sales

  datasource:
    url: jdbc:postgresql://${DB_HOST:192.168.1.122}:${DB_PORT:5432}/${DB_NAME:sales}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true

jwt:
   secret: superSecretKeyThatIsLongEnoughToBeSecure123
   expirationMs: 86400000